# As an alternative to a manual push to the prepublish branch, this workflow can
# be triggered on a release branch by assigning a special label to its pull
# request in order to set the CD circus in motion.

name: Prepublication staging

on:
  pull_request:
    types: [labeled]
    # Would filter by branch here, but GH Actions wrongly decides not to
    # trigger the workflow if we do this.

jobs:
  stage:
    runs-on: ubuntu-latest
    # Filtering by branch here instead. Credit due to @MiguelSavignano.
    # https://github.com/devmasx/merge-branch/issues/11
    if: contains(github.event.pull_request.head.ref, 'release/') || contains(github.event.pull_request.head.ref, 'hotfix/')
    steps:
      - uses: actions/checkout@v2
      - name: Merge into prepublish
        uses: devmasx/merge-branch@v1.3.0
        with:
          label_name: ready to launch
          target_branch: prepublish
          github_token: ${{ secrets.GITHUB_TOKEN }}
